name: food
description: Food App
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  equatable: ^2.0.5
  dartz: ^0.10.1
  flutter_bloc: ^8.1.1
  bloc: ^8.1.0
  get_it: ^7.2.0
  flutter_screenutil: ^5.5.4
  shared_preferences: ^2.2.2
  dio: ^5.3.2
  json_serializable: ^6.7.1
  flutter_easyloading: ^3.0.5
  carousel_slider: ^4.2.1
  fluttertoast: ^8.2.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
#    - assets/icons/



  fonts:
     - family: metropolis
       fonts:
         - asset: assets/fonts/metropolis/metropolis-black.otf
           weight: 900
         - asset: assets/fonts/metropolis/metropolis-bold.otf
           weight: 700
         - asset: assets/fonts/metropolis/metropolis-extra-bold.otf
           weight: 800
         - asset: assets/fonts/metropolis/metropolis-light.otf
           weight: 300
         - asset: assets/fonts/metropolis/metropolis-extra-light.otf
           weight: 200
         - asset: assets/fonts/metropolis/metropolis-medium.otf
           weight: 500
         - asset: assets/fonts/metropolis/metropolis-regular.otf
           weight: 400
         - asset: assets/fonts/metropolis/metropolis-semi-bold.otf
           weight: 600
         - asset: assets/fonts/metropolis/metropolis-thin.otf
           weight: 100

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
